### PR TITLE
feat: Add lazy support to available items grid

### LINKED ISSUE #130: Add support for Lazy Data Provider
It'd be great if we could use lazy data providers, just like in regular grids.

### PR DESCRIPTION
**Pull request by flang**
Close #130

## Summary by CodeRabbit

- **New Features**
  - Introduced in-memory and lazy filtering support for columns in the TwinColGrid component.
  - Added methods for managing items, filtering, and sorting in TwinColGrid.
  - Enhanced grid configuration with filterable columns, drag-and-drop, and reordering.

- **Enhancements**
  - Updated Book class to include a price field.
  - Improved column configuration in TwinColGrid to support sorting and headers.
  - Added support for eager and lazy filter configurations.

- **Bug Fixes**
  - Corrected initialization and layout logic in TwinColGrid.

- **Documentation**
  - Updated examples to reflect new features and enhancements.

### CODE REVIEW

**Comment by javier-godoy** [comment]
I decline to review because there are numerous formatting changes and other refactors in the implementation of the feature that have merits of their own, regardless of whether the feature is implemented or not. As this is currently presented, it's difficult to asses the actual impact on the API or to current features.

**Comment by mlopezFC** [comment]
@coderabbitai review

**Comment by mlopezFC** [comment]
@coderabbitai review

**Comment by mlopezFC** [comment]
After trying to review this PR a lot of times, we are not sure how much it would affect the stability of the component given  the amount of changes. So we're closing this for now and we will analyze if it is possible to create a simpler implementation in the future.

**Pull request closed without merging**
