### PR TITLE
Conventional commits

### PR DESCRIPTION
**Pull request by ngonzalezpazFC**

### CODE REVIEW

**Comment by javier-godoy** [comment]
@ngonzalezpazFC Please review

**Comment by ngonzalezpazFC** [comment]
> 
> 
> @ngonzalezpazFC Please review

I wonder about one commit, if [ bbd6084](https://github.com/FlowingCode/TwinColGridAddon/pull/61/commits/bbd60849e289ef54aa001badc1d21f6b4b343a98) needs the '!'. Other than that, LGTM.

**Comment by javier-godoy** [comment]
> > @ngonzalezpazFC Please review
> 
> I wonder about one commit, if [ bbd6084](https://github.com/FlowingCode/TwinColGridAddon/pull/61/commits/bbd60849e289ef54aa001badc1d21f6b4b343a98) needs the '!'. Other than that, LGTM.

It makes **as much sense** as separating features from fixes in the `demo` scope. IMHO, it doesn't. because we are not applying SemVer to the demos, we are not generating changelogs for them, and from the perspective of an end user those commits are just noise, but following the rationale of https://github.com/FlowingCode/GoogleMapsAddon/pull/15#issuecomment-748223983 "if we consider that the user of this, is a dependent project that is using the demos", then it's a breaking change for it. 

Ping @mlopezFC

**Review by mlopezFC — APPROVED** [review]
Regarding [this comment](https://github.com/FlowingCode/TwinColGridAddon/pull/61#issuecomment-749650903), I still think that it's important to have proper changelog of the demos. In a future possible improvement to analyze, we could decide to move the demos to a separated module, and in that case they would have changelog and semver, so this is a special case right now.

**Pull request merged**
