### PR TITLE
Add profile for creating a jar file with the demo classes

### PR DESCRIPTION
**Pull request by javier-godoy**

### CODE REVIEW

**Review by mlopezFC — COMMENTED** [review]
Wouldn't it be a good idea to add also test sources?

**Comment by javier-godoy** [comment]
@mlopezFC The goal of this PR is enabling Continuous Deployment on the demo site, which would basically aggregate test-jar artifacts from the addons. For that purpose only the test classes are required, since there should be no need to edit that project in an IDE, or consume the sources otherwise.

The test-jar classes will only be published in our snapshot/releases repository, mostly for consumption by addons demo project but they will not be published to the Vaadin directory. 

Please keep on hold util #37 is approved, since I need to exclude the test classes from the `directory` assembly, and I need that PR in order to do directory builds with my toolchain.

**Review by mlopezFC — APPROVED** [review]
Yes, you're right. I was thinking that having the sources available would help when working on the new demo, but now that I think deeper, you can always have the project with each addon also imported in the IDE.

**Comment by javier-godoy** [comment]
Indeed, the default assembly packaged the test JAR, so I had to remove it.

**Review by mlopezFC — APPROVED** [review]
Excellent, good catch

**Pull request merged**
